# Generated by Django 5.2.8 on 2025-12-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("default_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Template",
                "verbose_name_plural": "Inventory Templates",
                "ordering": ["default_order"],
            },
        ),
        migrations.CreateModel(
            name="StepTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("default_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Step Template",
                "verbose_name_plural": "Step Templates",
                "ordering": ["default_order"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("info_text", models.TextField(blank=True, null=True)),
                (
                    "help_url",
                    models.URLField(
                        help_text="Link to documentation support to perform the task",
                        null=True,
                    ),
                ),
                (
                    "work_url",
                    models.URLField(
                        help_text="Link to the source where the action must be applied (git, jira, ...)",
                        null=True,
                    ),
                ),
                (
                    "step_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="templates_management.steptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Template",
                "verbose_name_plural": "Task Templates",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_order", models.PositiveIntegerField(default=1)),
                ("field_name", models.CharField(max_length=200)),
                ("field_order", models.PositiveIntegerField(default=1)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("file", "File"),
                            ("password", "Password"),
                            ("datetime", "Datetime"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, help_text="Only allow admin to see the value"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="templates_management.inventorytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Field",
                "verbose_name_plural": "Template Fields",
                "ordering": ["group_order", "field_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "field_name", "field_order"),
                        name="unique_field_name_order_per_template",
                    )
                ],
            },
        ),
    ]
