# Generated by Django 5.2.8 on 2025-12-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="templatefield",
            name="unique_field_name_order_per_template",
        ),
        migrations.AddConstraint(
            model_name="templatefield",
            constraint=models.UniqueConstraint(
                fields=("template", "group_name", "field_name"),
                name="unique_field_name_and_group_name",
            ),
        ),
    ]
