# Generated by Django 5.2.8 on 2025-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="help_url",
            field=models.URLField(help_text="Link to documentation support to perform the task", null=True),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="info_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="work_url",
            field=models.URLField(
                help_text="Link to the source where the action must be applied (git, jira, ...)",
                null=True,
            ),
        ),
    ]
