# Generated by Django 5.2.8 on 2025-12-06 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "templates_management",
            "0002_tasktemplate_help_url_tasktemplate_info_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktemplate",
            name="info_url",
        ),
    ]
