# Generated by Django 5.2.8 on 2025-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "templates_management",
            "0002_remove_templatefield_unique_field_name_order_per_template_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
