# Generated by Django 5.2.8 on 2025-12-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_management", "0003_remove_tasktemplate_info_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("default_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Metadata Template",
                "verbose_name_plural": "Metadata Templates",
                "ordering": ["default_order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_order", models.PositiveIntegerField(default=1)),
                ("field_name", models.CharField(max_length=200)),
                ("field_order", models.PositiveIntegerField(default=1)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="templates_management.metadatatemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Field",
                "verbose_name_plural": "Template Fields",
                "ordering": ["group_order", "field_order"],
            },
        ),
    ]
