# Generated by Django 5.2.8 on 2025-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_management", "0003_templatefield_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktemplate",
            name="help_url",
            field=models.URLField(
                blank=True,
                help_text="Link to documentation support to perform the task",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasktemplate",
            name="work_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the source where the action must be applied (git, jira, ...)",
                null=True,
            ),
        ),
    ]
