# Generated by Django 6.0 on 2025-12-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_management", "0004_alter_tasktemplate_help_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorytemplate",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="steptemplate",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="steptemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
