# Generated by Django 6.0 on 2026-01-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_management", "0005_rename_name_inventorytemplate_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_order", models.PositiveIntegerField(default=1)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="templates_management.inventorytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Template",
                "verbose_name_plural": "Groups Templates",
                "ordering": ["group_order", "group_name"],
            },
        ),
        migrations.CreateModel(
            name="FieldTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=200)),
                ("field_order", models.PositiveIntegerField(default=1)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("longtext", "Long text"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("file", "File"),
                            ("password", "Password"),
                            ("datetime", "Datetime"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, help_text="Only allow admin to see the value"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="templates_management.grouptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Template",
                "verbose_name_plural": "Fields Templates",
                "ordering": ["field_order", "field_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="grouptemplate",
            constraint=models.UniqueConstraint(fields=("template", "group_name"), name="unique_group_name_by_inventory"),
        ),
        migrations.AddConstraint(
            model_name="fieldtemplate",
            constraint=models.UniqueConstraint(
                fields=("group_template", "field_name"),
                name="unique_field_name_by_group",
            ),
        ),
    ]
