# Generated by Django 6.0 on 2026-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_inventoryfield_group_name_and_more"),
        ("templates_management", "0006_grouptemplate_fieldtemplate_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="templatefield",
            name="unique_field_name_and_group_name",
        ),
        migrations.AddField(
            model_name="grouptemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="TemplateField",
        ),
    ]
