# Generated by Django 5.2.8 on 2025-12-12 16:12

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        (
            "templates_management",
            "0002_remove_templatefield_unique_field_name_order_per_template_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Custom title, overrides template name",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(max_length=10)),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this step was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_management.inventorytemplate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="InventoryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_order", models.PositiveIntegerField(default=1)),
                ("field_name", models.CharField(max_length=200)),
                ("field_order", models.PositiveIntegerField(default=1)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("file", "File"),
                            ("password", "Password"),
                            ("datetime", "Datetime"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "text_value",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "number_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "file_value",
                    models.FileField(blank=True, null=True, upload_to="inventory_files/"),
                ),
                (
                    "password_value",
                    encrypted_fields.fields.EncryptedTextField(blank=True, max_length=500, null=True),
                ),
                ("datetime_value", models.DateTimeField(blank=True, null=True)),
                (
                    "field_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this task was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_management.templatefield",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="inventory.projectinventory",
                    ),
                ),
            ],
        ),
    ]
