# Generated by Django 5.2.8 on 2025-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryfield",
            name="file_value",
            field=models.TextField(blank=True, default=""),
        ),
    ]
