# Generated by Django 5.2.8 on 2025-12-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventoryfield_file_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryfield",
            name="number_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
