# Generated by Django 5.2.8 on 2025-12-13 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_inventoryfield_number_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectinventory",
            old_name="name",
            new_name="title",
        ),
    ]
