# Generated by Django 6.0 on 2025-12-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_rename_name_projectinventory_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinventory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
