# Generated by Django 6.0 on 2026-01-31 15:44

import django.db.models.deletion
from django.db import migrations, models


def delete_all_fields(apps, schema_editor):
    Field = apps.get_model("inventory", "InventoryField")
    Field.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_projectinventory_description"),
        ("templates_management", "0006_grouptemplate_fieldtemplate_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_all_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="inventoryfield",
            name="group_name",
        ),
        migrations.RemoveField(
            model_name="inventoryfield",
            name="group_order",
        ),
        migrations.RemoveField(
            model_name="inventoryfield",
            name="inventory",
        ),
        migrations.AlterField(
            model_name="inventoryfield",
            name="field_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this task was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates_management.fieldtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("longtext", "Long text"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("file", "File"),
                    ("password", "Password"),
                    ("datetime", "Datetime"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InventoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "group_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this group was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_management.grouptemplate",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="inventory.projectinventory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="inventoryfield",
            name="group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="inventory.inventorygroup",
            ),
            preserve_default=False,
        ),
    ]
