# Generated by Django 6.0 on 2026-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_inventoryfield_group_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryfield",
            name="text_value",
            field=models.TextField(blank=True, default=""),
        ),
    ]
