# Generated by Django 6.0 on 2026-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_inventoryfield_text_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryfield",
            name="is_secret",
            field=models.BooleanField(default=False, help_text="Only allow admin to see the value"),
        ),
    ]
