# Generated by Django 5.2.8 on 2025-12-07 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_projecttask_comment_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ProjectStep",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "title",
                            models.CharField(
                                help_text="Custom title, overrides template name",
                                max_length=200,
                            ),
                        ),
                        ("icon", models.CharField(max_length=10)),
                        ("order", models.IntegerField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="steps",
                                to="projects.project",
                            ),
                        ),
                        (
                            "step_template",
                            models.ForeignKey(
                                blank=True,
                                help_text="Template this step was created from",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="templates_management.steptemplate",
                            ),
                        ),
                        (
                            "description",
                            models.TextField(blank=True),
                        ),
                    ],
                    options={
                        "ordering": ["order"],
                        "unique_together": {("project", "order")},
                    },
                ),
                migrations.CreateModel(
                    name="ProjectTask",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "title",
                            models.CharField(help_text="Custom title, overrides template", max_length=500),
                        ),
                        ("order", models.IntegerField()),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("done", "Done"),
                                    ("na", "N/A"),
                                ],
                                default="pending",
                                max_length=10,
                            ),
                        ),
                        ("completed_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "project_step",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="tasks",
                                to="projects.projectstep",
                            ),
                        ),
                        (
                            "task_template",
                            models.ForeignKey(
                                blank=True,
                                help_text="Template this task was created from",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="templates_management.tasktemplate",
                            ),
                        ),
                        (
                            "manually_created",
                            models.BooleanField(
                                default=False,
                                help_text="Indicates if the task was created manually or from a template",
                            ),
                        ),
                        (
                            "completed_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "help_url",
                            models.URLField(help_text="Link to documentation support to perform the task", null=True),
                        ),
                        (
                            "info_text",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "work_url",
                            models.URLField(
                                help_text="Link to the source where the action must be applied (git, jira, ...)",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["order"],
                        "unique_together": {("project_step", "order")},
                    },
                ),
                migrations.CreateModel(
                    name="TaskComment",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("comment_text", models.TextField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "project_task",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="comments",
                                to="projects.projecttask",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["created_at"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE projects_projectstep RENAME TO checklist_projectstep;
                        ALTER TABLE projects_projecttask RENAME TO checklist_projecttask;
                        ALTER TABLE projects_taskcomment RENAME TO checklist_taskcomment;
                    """,
                    reverse_sql="""
                        ALTER TABLE checklist_projectstep RENAME TO projects_projectstep;
                        ALTER TABLE checklist_projecttask RENAME TO projects_projecttask;
                        ALTER TABLE checklist_taskcomment RENAME TO projects_taskcomment;
                    """,
                ),
            ],
        ),
    ]
