# Generated by Django 6.0 on 2025-12-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectstep",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
