# Generated by Django 5.2.8 on 2025-11-26 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("templates_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Custom title, overrides template name",
                        max_length=200,
                    ),
                ),
                ("icon", models.CharField(max_length=10)),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="projects.project",
                    ),
                ),
                (
                    "step_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this step was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_management.steptemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Custom title, overrides template", max_length=500),
                ),
                ("info_url", models.URLField(blank=True, null=True)),
                ("order", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("na", "N/A"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Simple comment field (Phase 1)"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.projectstep",
                    ),
                ),
                (
                    "task_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this task was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_management.tasktemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project_step", "order")},
            },
        ),
    ]
