# Generated by Django 6.0 on 2026-01-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="expected_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
