# Generated by Django 5.2.8 on 2025-12-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="manually_created",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the task was created manually or from a template",
            ),
        ),
    ]
