# Generated by Django 5.2.8 on 2025-12-05 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_taskcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
    ]
