# Generated by Django 5.2.8 on 2025-12-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttask",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="projecttask",
            name="info_url",
        ),
        migrations.RemoveField(
            model_name="projecttask",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="projectstep",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="help_url",
            field=models.URLField(help_text="Link to documentation support to perform the task", null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="info_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="work_url",
            field=models.URLField(
                help_text="Link to the source where the action must be applied (git, jira, ...)",
                null=True,
            ),
        ),
    ]
